### PR TITLE
Only allow rhotator logic to work when one of the tools is in the inventory

### LINKED ISSUE #293: Rhotator tools should only work when in the inventory
Currently, the effect of the rhotator tool keeps working when it is removed from your inventory, it should be disabled once it is removed

### PR DESCRIPTION
**Pull request by oversword**
Check if any rhotator tool is anywhere in the main player inventory, if not exit the logic

Fixes https://github.com/BlockySurvival/issue-tracker/issues/293

### CODE REVIEW

**Comment by entuland** [comment]
Thanks for the pull request - the approach you used though would change the default behavior on existing installations and would impose it on all players in a world without giving any choice.

I pushed this commit allowing each player to decide about that behavior with a new chat command: https://github.com/entuland/rhotator/commit/079c95ea33068f84c48c6af9a5c265fb5dc9c89d

I hope the above is good enough for your needs.

**Comment by oversword** [comment]
@entuland okay I can appreciate you want the customisability, one thing I would suggest is the ability to set the default with a server setting

**Comment by entuland** [comment]
@oversword how would you like such a default to behave?

Should it only apply to new players that have never set a preference of their own (and once they set such a preference, their choice would take precedence over the server default) or do you want the server default to take precedence over the player choice at any time?

As of right now new players start with the rotation memory off, this means that even if the `require_tool` flag is off, the blocks they place would be placed with the existing mechanics with no interference from this mod.

Only after they explicitly set the memory for themselves (either using the memory tool, the multitool or a chat command) they would become able to place nodes with the rotation memory without any tool in their inventory.

**Comment by oversword** [comment]
@entuland yeah it should not overwrite the user's choice, it should just be the default if they have never made a choice so that a server can switch it on if that's what they think the expected behaviour is.

The default should be false (off) to maintain existing functionality, it would only be switched on if a server desired it.

I mentioned this feature because, if I understand the code correctly, once a user has set the value it will be remembered for them forever - this is good, but I do think a server would want to switch "require_tool" on by default so that's it's more intuitive for new users. If I'm wrong about this let me know, maybe there is a better solution.

If we wanted to allow a server to force it "on" then we would also want a setting to "allow_require_tool_choice", if that were false then whatever the server sets as the default could not be changed by any user - I'm not sure anyone would want to remove choice though

**Comment by entuland** [comment]
@oversword please see https://github.com/entuland/rhotator/commit/b80a3fe6f933b5c254996de853dc2c00d5bc3e7b - hopefully I haven't messed anything up and you should be able to define a default for new players and any existing player that hasn't expressed a personal preference yet.

**Comment by oversword** [comment]
@entuland  that looks good to me, thanks for your work :)

**Comment by entuland** [comment]
You're welcome @oversword, thanks for using my mod!

**Pull request closed without merging**
